base: /
title: Lumen Pink # Site title
sitename: A nova rede social da Lumen # Site name
support: # File extensions which will be parsed (must be an array)
  - md
  - txt
  - html
  - htm
buildall: true # Whether to build pages without frontmatter
outputdir: _site # Output directory
#  (there's a bug in the YAML interpreter that prevents 
# parsing when comments are in the same line as short arrays) 
defaultcategory: "General" # Default category 
lang: [ pt-br, en, es ]  # Supported languages (must be an array - first is the default)
fqdn: https://lumen.pink # FQDN without trailing slash
author: ~lumen # Author name
htmlpostprocessing: minify # minify or beautify or none