services:
  indieinabox:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: indieinabox_app
    ports:
      - "8081:8081"
    volumes:
      # Mapeia todo o projeto para dentro do container
      - .:/app
    environment:
      - ENVIRONMENT=development
    # Rodar o servidor embutido do PHP (caso não seja sobrescrito)
    command: php -S 0.0.0.0:8081 build.php
