<?php

declare(strict_types=1);

namespace Indieinabox\Core;

/**
 * Class Version
 *
 * Provides application version information, git commit metadata, and build timestamps.
 */
class Version
{
    /**
     * Semantic version string of the current release.
     */
    public const VERSION = '0.2.0';

    /**
     * Gets the full version string including build metadata.
     *
     * @return string
     */
    public static function get(): string
    {
        if (defined('INDIEINABOX_COMPILED_VERSION')) {
            return (string) constant('INDIEINABOX_COMPILED_VERSION');
        }

        // In development mode, check if a VERSION file exists (e.g., generated by cccp.sh)
        $versionFile = dirname(__DIR__, 2) . '/VERSION';
        if (file_exists($versionFile)) {
            $fileVersion = trim((string) @file_get_contents($versionFile));
            if ($fileVersion !== '') {
                return $fileVersion;
            }
        }

        $baseVersion = self::VERSION;
        $gitCommit = self::getGitCommitHash();
        if ($gitCommit !== null) {
            return $baseVersion . '+git.' . $gitCommit;
        }

        return $baseVersion;
    }

    /**
     * Retrieves the short git commit hash if running within a git repository.
     *
     * @return string|null
     */
    public static function getGitCommitHash(): ?string
    {
        $gitDir = dirname(__DIR__, 2) . '/.git';
        if (!is_dir($gitDir)) {
            return null;
        }

        $headFile = $gitDir . '/HEAD';
        if (!file_exists($headFile)) {
            return null;
        }

        $head = trim((string) @file_get_contents($headFile));
        if (strpos($head, 'ref: ') === 0) {
            $ref = substr($head, 5);
            $refPath = $gitDir . '/' . $ref;
            if (file_exists($refPath)) {
                $hash = trim((string) @file_get_contents($refPath));
                return substr($hash, 0, 7);
            }
            $packedRefsFile = $gitDir . '/packed-refs';
            if (file_exists($packedRefsFile)) {
                $lines = @file($packedRefsFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
                if (is_array($lines)) {
                    foreach ($lines as $line) {
                        if (str_starts_with($line, '#') || str_starts_with($line, '^')) {
                            continue;
                        }
                        $parts = explode(' ', trim($line), 2);
                        if (count($parts) === 2 && $parts[1] === $ref && strlen($parts[0]) >= 7) {
                            return substr($parts[0], 0, 7);
                        }
                    }
                }
            }
        } elseif (strlen($head) >= 7) {
            return substr($head, 0, 7);
        }

        if (function_exists('exec')) {
            $output = [];
            $code = 0;
            @exec('git rev-parse --short HEAD 2>/dev/null', $output, $code);
            if ($code === 0 && !empty($output[0]) && preg_match('/^[a-f0-9]{7,40}$/i', trim($output[0]))) {
                return trim($output[0]);
            }
        }

        return null;
    }

    /**
     * Gets the base semantic version string.
     *
     * @return string
     */
    public static function getBaseVersion(): string
    {
        return self::VERSION;
    }

    /**
     * Checks if the application is currently running as a single compiled executable.
     *
     * @return bool
     */
    public static function isCompiled(): bool
    {
        return defined('INDIEINABOX_COMPILED_VERSION');
    }

    /**
     * Gets the build timestamp if available.
     *
     * @return string|null
     */
    public static function getBuildDate(): ?string
    {
        if (defined('INDIEINABOX_BUILD_DATE')) {
            return (string) constant('INDIEINABOX_BUILD_DATE');
        }

        $versionFile = dirname(__DIR__, 2) . '/VERSION';
        if (file_exists($versionFile)) {
            $mtime = @filemtime($versionFile);
            if ($mtime !== false && $mtime > 0) {
                return date('c', $mtime);
            }
        }

        if (function_exists('exec')) {
            $output = [];
            $code = 0;
            @exec('git log -1 --format=%cI 2>/dev/null', $output, $code);
            if ($code === 0 && !empty($output[0])) {
                return trim($output[0]);
            }
        }

        return null;
    }

    /**
     * Extracts a SemVer version string from release metadata (tag name, release name, or description body).
     *
     * @param array<string, mixed> $release
     * @return string|null
     */
    public static function extractVersionFromRelease(array $release): ?string
    {
        $pattern = '/\bv?(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)\b/';

        $tagName = isset($release['tag_name']) ? (string) $release['tag_name'] : '';
        if ($tagName !== '' && strtolower($tagName) !== 'nightly' && preg_match($pattern, $tagName, $matches)) {
            return $matches[1];
        }

        $name = isset($release['name']) ? (string) $release['name'] : '';
        if ($name !== '' && preg_match($pattern, $name, $matches)) {
            return $matches[1];
        }

        $body = isset($release['body']) ? (string) $release['body'] : '';
        if ($body !== '' && preg_match('/Version:\s*v?(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)/i', $body, $matches)) {
            return $matches[1];
        }

        return null;
    }

    /**
     * Determines whether a remote version/release is strictly newer than the current version/release.
     *
     * @param string $remoteVersion Remote SemVer version or release tag.
     * @param string|null $currentVersion Current SemVer version (defaults to Version::get()).
     * @param string|null $remoteDate Remote release published date in ISO 8601 format.
     * @param string|null $currentDate Current build/commit date in ISO 8601 format (defaults to Version::getBuildDate()).
     * @return bool
     */
    public static function isNewerVersion(
        string $remoteVersion,
        ?string $currentVersion = null,
        ?string $remoteDate = null,
        ?string $currentDate = null
    ): bool {
        $currentVersion = $currentVersion ?? self::get();
        $currentDate = $currentDate ?? self::getBuildDate();

        $cleanRemote = ltrim($remoteVersion, 'vV');
        $cleanCurrent = ltrim($currentVersion, 'vV');

        $remoteParts = explode('+', $cleanRemote, 2);
        $currentParts = explode('+', $cleanCurrent, 2);

        $remoteSemver = $remoteParts[0];
        $currentSemver = $currentParts[0];

        $isRemoteSemver = (bool) preg_match('/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/', $remoteSemver);
        $isCurrentSemver = (bool) preg_match('/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/', $currentSemver);

        if ($isRemoteSemver && $isCurrentSemver) {
            $cmp = version_compare($remoteSemver, $currentSemver);
            if ($cmp > 0) {
                return true;
            }
            if ($cmp < 0) {
                return false;
            }

            // Base and prerelease are identical, compare build metadata if both present
            if (isset($remoteParts[1], $currentParts[1]) && $remoteParts[1] !== $currentParts[1]) {
                $metaCmp = version_compare($remoteParts[1], $currentParts[1]);
                if ($metaCmp > 0) {
                    return true;
                }
                if ($metaCmp < 0) {
                    return false;
                }
            }
        }

        // Date-based comparison fallback (e.g. non-semver nightly tags, or equal semver)
        if ($remoteDate !== null && $currentDate !== null) {
            $remoteTs = strtotime($remoteDate);
            $currentTs = strtotime($currentDate);
            if ($remoteTs !== false && $currentTs !== false) {
                return $remoteTs > $currentTs;
            }
        }

        return false;
    }
}
